const fs=require('fs'),path=require('path');
function loadEnv(f){const p=path.resolve(process.cwd(),f);if(!fs.existsSync(p))return;fs.readFileSync(p,'utf8').split('\n').forEach(l=>{const t=l.trim();if(!t||t.startsWith('#'))return;const eq=t.indexOf('=');if(eq<0)return;const k=t.slice(0,eq).trim(),v=t.slice(eq+1).trim().replace(/^["']|["']$/g,'');if(!process.env[k])process.env[k]=v;});}
loadEnv('.env.local');
const BASE=( process.env.TURSO_DATABASE_URL??'').replace(/^libsql:\/\//,'https://'),TOKEN=process.env.TURSO_AUTH_TOKEN??'';
if(!BASE||!TOKEN){console.error('\n❌  Set TURSO_DATABASE_URL and TURSO_AUTH_TOKEN in .env.local\n');process.exit(1);}
async function sql(q,a=[]){const m=a.map(v=>v===null||v===undefined?{type:'null'}:typeof v==='number'?{type:Number.isInteger(v)?'integer':'float',value:String(v)}:{type:'text',value:String(v)});const r=await fetch(`${BASE}/v2/pipeline`,{method:'POST',headers:{Authorization:`Bearer ${TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({requests:[{type:'execute',stmt:{sql:q,...(m.length?{args:m}:{})}},{type:'close'}]})});const j=await r.json();if(!r.ok)throw new Error(j?.message??`HTTP ${r.status}`);const rs=j.results?.[0];if(rs?.type==='error')throw new Error(rs.error?.message??'SQL error');return rs?.response?.result??{};}
const SCHEMA=[
['CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE COLLATE NOCASE, email TEXT NOT NULL UNIQUE COLLATE NOCASE, password_hash TEXT NOT NULL, first_name TEXT NOT NULL, middle_name TEXT, last_name TEXT NOT NULL, birthday TEXT, phone_number TEXT, full_address TEXT, gov_id_path TEXT, profile_pic TEXT, role TEXT NOT NULL DEFAULT \'user\' CHECK (role IN (\'user\',\'admin\',\'moderator\')), account_status TEXT NOT NULL DEFAULT \'active\' CHECK (account_status IN (\'active\',\'suspended\',\'banned\',\'pending\')), is_verified INTEGER NOT NULL DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)','users'],
['CREATE TABLE IF NOT EXISTS item_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, description TEXT, icon TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)','item_categories'],
['CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, category_id INTEGER REFERENCES item_categories(id) ON DELETE SET NULL, title TEXT NOT NULL, description TEXT, condition TEXT NOT NULL DEFAULT \'good\', borrow_type TEXT NOT NULL DEFAULT \'free\', fee_per_day REAL DEFAULT 0, max_borrow_days INTEGER DEFAULT 7, location TEXT, image_path TEXT, is_available INTEGER NOT NULL DEFAULT 1, is_active INTEGER NOT NULL DEFAULT 1, borrow_count INTEGER NOT NULL DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)','items'],
['CREATE TABLE IF NOT EXISTS borrows (id INTEGER PRIMARY KEY AUTOINCREMENT, item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE, borrower_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, owner_id INTEGER NOT NULL REFERENCES users(id), borrow_date TEXT NOT NULL, due_date TEXT NOT NULL, return_date TEXT, status TEXT NOT NULL DEFAULT \'pending\', total_fee REAL DEFAULT 0, payment_status TEXT DEFAULT \'unpaid\', borrower_note TEXT, owner_note TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)','borrows'],
['CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, borrow_id INTEGER NOT NULL UNIQUE REFERENCES borrows(id) ON DELETE CASCADE, reviewer_id INTEGER NOT NULL REFERENCES users(id), reviewee_id INTEGER REFERENCES users(id), item_id INTEGER REFERENCES items(id), rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5), comment TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)','reviews'],
['CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, title TEXT NOT NULL, body TEXT, is_read INTEGER NOT NULL DEFAULT 0, link TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)','notifications'],
['CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, receiver_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, borrow_id INTEGER REFERENCES borrows(id) ON DELETE SET NULL, body TEXT NOT NULL, is_read INTEGER NOT NULL DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)','messages'],
['CREATE INDEX IF NOT EXISTS idx_items_owner ON items(owner_id)','idx_items_owner'],
['CREATE INDEX IF NOT EXISTS idx_borrows_borrower ON borrows(borrower_id)','idx_borrows_borrower'],
['CREATE INDEX IF NOT EXISTS idx_notifs_user ON notifications(user_id)','idx_notifs_user'],
];
const SEEDS=["INSERT OR IGNORE INTO item_categories (name,description,icon) VALUES ('Tools & Equipment','Hand tools, power tools','🔧'),('Kitchen & Appliances','Cookware, appliances','🍳'),('Books & Learning','Books, educational materials','📚'),('Sports & Recreation','Sports gear, outdoor equipment','⚽'),('Electronics','Cameras, projectors, gadgets','📷'),('Furniture & Home','Tables, chairs, decorations','🪑'),('Baby & Kids','Strollers, toys, baby gear','🍼'),('Events & Parties','Tables, tents, party supplies','🎉')"];
async function run(){
  console.log('\n🔧  Creating schema…\n');
  for(const[q,n]of SCHEMA){try{await sql(q);console.log(`  ✅  ${n}`);}catch(e){console.error(`  ❌  ${n}: ${e.message}`);}}
  console.log('\n🌱  Seeding…\n');
  for(const q of SEEDS){try{await sql(q);console.log('  ✅  categories seeded');}catch(e){console.error('  ❌ ',e.message);}}
  console.log('\n✨  Done!\n');
}
run().catch(e=>{console.error('\n❌ ',e.message);process.exit(1);});
